version: '3.2'
services:
  server:
    build: ./sandbox
    depends_on:
      - redis
    ports:
      - 8000:8000
    volumes:
      - ./sandbox:/home/user/sandbox
    network_mode: host

  web:
    build: ./nuxt
    depends_on:
      - server
    ports:
      - 3000:3000
    volumes:
      - ./nuxt:/home/user
    network_mode: host

  redis:
    image: redis
    ports:
      - 6379:6379
    network_mode: host
