# Generated by Django 2.2.6 on 2019-10-11 14:28

from django.db import migrations, models
import django.db.models.deletion


def initial_problem(apps, schema):
    # default problem
    Problem = apps.get_model('problem', 'Problem')
    Problem.objects.create(
        title='two sum',
        description='create a function named \'two_sum\' with two parameters (a, b) that adds up two numbers',
        run_script="assert two_sum(1, 2) == 3, 'two_sum(1, 2) returns {}'.format(two_sum(1, 2))\nprint('two_sum(1, 2) = {}'.format(two_sum(1, 2)))"
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('run_script', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('evaluated', models.BooleanField(default=False)),
                ('error', models.TextField(default='')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='problem.Problem')),
            ],
        ),
        migrations.RunPython(initial_problem)
    ]
