# Generated by Django 2.2.6 on 2019-11-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='output_type',
            field=models.CharField(choices=[('text/plain', 'text/plain'), ('text/html', 'text/html')], default='text/plain', max_length=64),
        ),
    ]
